inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - ruby-units.gemspec
    - bin/*
Style/CaseEquality:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
